---

platform: linux

image_resource:
  type: docker-image
  source:
    repository: python
    tag: 3.6

inputs:
  - name: dp-conceptual-search

outputs:
  - name: build

run:
  path: dp-conceptual-search/ci/scripts/build.sh
